#!/bin/bash

# Set environment variables to cut down on annoying warning messages
export DEBIAN_FRONTEND='noninteractive'
export DEBCONF_NOWARNINGS='true'
export HOME=/root
export LC_ALL=C

echo '----------------------'
echo 'apt-get install -y git'
apt-get install -y git

echo '-------------------------'
echo 'apt-get install -y puppet'
apt-get install -y puppet

echo '+++++++++++++++++++++'
echo 'BEGIN installing Chef'
echo '---------------------------------------'
echo 'apt-get install -y curl ca-certificates'
apt-get install -y curl ca-certificates
echo '-------------------------------------------------------'
echo 'curl -L https://www.opscode.com/chef/install.sh | bash;'
curl -L https://www.opscode.com/chef/install.sh | bash;
rm -f /tmp/chef*deb;
chef-solo -v
echo 'FINISHED installing Chef'
echo '++++++++++++++++++++++++'

echo '------------------------------------'
echo 'apt-get install -y python2.7 ansible'
apt-get install -y python2.7 ansible

# Needed for Heroku
echo '----------------------------------------------------------'
echo 'apt-get install -y git wget ca-certificates openssh-client'
apt-get install -y git wget ca-certificates openssh-client
