#!/bin/bash

SECONDS=0
sudo /usr/local/bin/docker-root-aptget

echo '--------------------------------------------'
echo 'sudo apt-get install -y curl ca-certificates'
sudo apt-get install -y curl ca-certificates

echo '*******************************'
echo 'BEGIN transforming min into dev'
echo '*******************************'

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/user1.sh | bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/user2.sh | bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/check.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

echo '**********************************'
echo 'FINISHED transforming min into dev'
echo '**********************************'

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-user.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"
