#!/bin/bash

echo '++++++++++++++++++++++++++++++++++'
echo 'BEGIN sanity checks (Hyde Edition)'

echo '------'
echo 'whoami'
whoami

echo '--------------'
echo 'sudo --version'
sudo --version

echo '--------------'
echo 'nano --version'
nano --version

echo '--------------'
echo 'tree --version'
tree --version

echo '-------'
echo 'tmux -V'
tmux -V

echo '-----------------------'
echo 'puppet master --version'
puppet master --version

echo '------------'
echo 'chef-solo -v'
chef-solo -v

echo '-----------------'
echo 'ansible --version'
ansible --version

echo '--------------'
echo 'heroku version'
heroku version

echo '----------------'
echo 'python --version'
python --version

echo '--------------'
echo 'hyde --version'
hyde --version

echo 'FINISHED sanity checks (Hyde Edition)'
echo '+++++++++++++++++++++++++++++++++++++'
