#!/bin/bash

# Set environment variables to cut down on annoying warning messages
export DEBIAN_FRONTEND='noninteractive'
export DEBCONF_NOWARNINGS='true'
export HOME=/root
export LC_ALL=C

echo '---------------------------------------'
echo 'apt-get install -y python2.7 python-pip'
apt-get install -y python2.7 python-pip

echo '----------------'
echo 'pip install hyde'
pip install hyde
