#!/bin/bash

echo '******************************'
echo 'BEGIN installing Ruby on Rails'
echo '******************************'

# BEGIN: activate rbenv
export PATH="/home/winner/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
# END: activate rbenv

# BEGIN: activate NVM
export NVM_DIR="/home/winner/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use --lts # Activate Node

# Set of gems to install for each version of Ruby
function install_gems {
  echo '-------------------'
  echo 'gem install bundler'
  gem install bundler

  # The latest versions of Rails, PostgreSQL, Nokogiri, and MailCatcher
  echo '-----------------'
  echo 'gem install rails'
  gem install rails
  echo '--------------'
  echo 'gem install pg'
  gem install pg
  echo '--------------------'
  echo 'gem install nokogiri'
  gem install nokogiri
  echo '-----------------------'
  echo 'gem install mailcatcher'
  gem install mailcatcher

  
  echo '------------------------'
  echo 'gem install pg -v 0.18.4'
  gem install pg -v 0.18.4
  echo '-----------------------------'
  echo 'gem install nokogiri -v 1.6.8'
  gem install nokogiri -v 1.6.8
  echo '----------------------------'
  echo 'gem install rails -v 5.0.0.1'
  gem install rails -v 5.0.0.1
}

# Input parameter: 'ruby-x.y'
function install_ruby_version {
  ruby_version=$1
  echo '+++++++++++++++++++++++++++++++++++++'
  echo "rbenv install $ruby_version --verbose"
  rbenv install $ruby_version --verbose
  rbenv global $ruby_version
  install_gems
}

# Latest versions of Ruby
# https://www.ruby-lang.org/en/downloads/
time install_ruby_version 2.3.1
echo 'The time it took to install Ruby 2.3.1 and various gems is printed above.'
echo '-------------------------------------------------------------------------'

rbenv global 2.3.1

echo '*********************************'
echo 'FINISHED installing Ruby on Rails'
echo '*********************************'

echo '*******************'
echo 'BEGIN sanity checks'

echo '------'
echo 'whoami'
whoami

echo '--------------'
echo 'sudo --version'
sudo --version

echo '--------------'
echo 'nano --version'
nano --version

echo '--------------'
echo 'tree --version'
tree --version

echo '-------'
echo 'tmux -V'
tmux -V

echo '-----------------------'
echo 'puppet master --version'
puppet master --version

echo '------------'
echo 'chef-solo -v'
chef-solo -v

echo '-----------------'
echo 'ansible --version'
ansible --version

echo '--------------'
echo 'heroku version'
heroku version

echo '---------------'
echo 'redis-server -v'
redis-server -v

echo '----------------'
echo 'sqlite3 -version'
sqlite3 -version

echo '--------------'
echo 'psql --version'
psql --version

echo '--------------'
echo 'command -v nvm'
command -v nvm

echo '-------------'
echo 'nvm --version'
nvm --version

echo '-----------'
echo 'npm version'
npm version

echo '-------'
echo 'node -v'
node -v

echo '----------'
echo 'type rbenv'
type rbenv

echo '--------------'
echo 'rbenv versions'
rbenv versions

echo '-------'
echo 'ruby -v'
ruby -v

echo '--------'
echo 'rails -v'
rails -v

echo '------------------'
echo 'gem list "^rails$"'
gem list "^rails$"

echo '---------------------'
echo 'gem list "^nokogiri$"'
gem list "^nokogiri$"

echo '---------------'
echo 'gem list "^pg$"'
gem list "^pg$"

echo '------------------------'
echo 'gem list "^mailcatcher$"'
gem list "^mailcatcher$"

echo 'COMPLETED sanity checks'
echo '***********************'
