#!/bin/bash

SECONDS=0
sudo /usr/local/bin/docker-root-aptget

echo '*****************************************'
echo 'BEGIN transforming dev into rbenv-general'
echo '*****************************************'

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/rbenv-general/root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/rbenv-general/user.sh | bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/rbenv-general/check.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

echo '********************************************'
echo 'FINISHED transforming dev into rbenv-general'
echo '********************************************'

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-user.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"
