#!/bin/bash

echo '******************************'
echo 'BEGIN installing Ruby on Rails'
echo '******************************'

# Set of gems to install for each version of Ruby
function install_gems {
  echo '-------------------'
  echo 'gem install bundler'
  gem install bundler

  echo '------------------'
  echo 'gem install jekyll'
  gem install jekyll
}

# Input parameter: 'ruby-x.y'
function install_ruby_version {
  ruby_version=$1
  echo '+++++++++++++++++++++++++++++++++++++'
  echo "rbenv install $ruby_version --verbose"
  rbenv install $ruby_version --verbose
  rbenv global $ruby_version
  install_gems
}

# Allow rbenv commands to work
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv

# Latest versions of Ruby
# https://www.ruby-lang.org/en/downloads/
time install_ruby_version 2.3.1
echo 'The time it took to install Ruby 2.3.1 and various gems is printed above.'
echo '-------------------------------------------------------------------------'
rbenv global 2.3.1

echo '*********************************'
echo 'FINISHED installing Ruby on Rails'
echo '*********************************'

echo '*******************'
echo 'BEGIN sanity checks'

echo '------'
echo 'whoami'
whoami

echo '--------------'
echo 'sudo --version'
sudo --version

echo '--------------'
echo 'nano --version'
nano --version

echo '--------------'
echo 'tree --version'
tree --version

echo '-------'
echo 'tmux -V'
tmux -V

echo '-----------------------'
echo 'puppet master --version'
puppet master --version

echo '------------'
echo 'chef-solo -v'
chef-solo -v

echo '-----------------'
echo 'ansible --version'
ansible --version

echo '--------------'
echo 'heroku version'
heroku version

echo '---------------'
echo 'redis-server -v'
redis-server -v

echo '----------------'
echo 'sqlite3 -version'
sqlite3 -version

echo '--------------'
echo 'psql --version'
psql --version

echo '---------'
echo 'nodejs -v'
nodejs -v

echo '----------'
echo 'type rbenv'
type rbenv

echo '--------------'
echo 'rbenv versions'
rbenv versions

echo '-------'
echo 'ruby -v'
ruby -v

echo '------------------'
echo 'gem list "^jekyll$"'
gem list "^jekyll$"

echo 'COMPLETED sanity checks'
echo '***********************'
