#!/bin/bash

SECONDS=0

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/aptget.sh | sudo bash

echo '****************************************'
echo 'BEGIN transforming dev into rbenv-jekyll'
echo '****************************************'

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/rbenv-jekyll/root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/rbenv-jekyll/user.sh | bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/rbenv-jekyll/check.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

echo '*******************************************'
echo 'FINISHED transforming dev into rbenv-jekyll'
echo '*******************************************'

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-user.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"
