#!/bin/bash

echo '**********************'
echo 'BEGIN installing rbenv'
echo '**********************'

echo '---------------------------'
echo 'BEGIN installation of rbenv'
echo 'git clone https://github.com/sstephenson/rbenv.git /home/winner/.rbenv'
git clone https://github.com/sstephenson/rbenv.git /home/winner/.rbenv
wait
echo 'Updating /home/winner/.bashrc'
echo 'export PATH="/home/winner/.rbenv/bin:$PATH"' >> /home/winner/.bashrc
echo 'eval "$(rbenv init -)"' >> /home/winner/.bashrc
export PATH="/home/winner/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv
echo 'FINISHED installation of rbenv'
echo '------------------------------'

echo '--------------------------------'
echo 'BEGIN installation of ruby-build'
git clone https://github.com/sstephenson/ruby-build.git /home/winner/.rbenv/plugins/ruby-build
wait
echo 'FINISHED installation of ruby-build'
echo '-----------------------------------'

echo '-----------------------------------------'
echo 'BEGIN installation of rbenv-communal-gems'
mkdir -p /home/winner/.rbenv/plugins
git clone git://github.com/tpope/rbenv-communal-gems.git \
  /home/winner/.rbenv/plugins/rbenv-communal-gems
wait
rbenv communize --all
echo 'FINISHED installation of rbenv-communal-gems'
echo '--------------------------------------------'

echo '--------------------------------------'
echo 'BEGIN installation of rbenv-gem-rehash'
git clone https://github.com/sstephenson/rbenv-gem-rehash.git /home/winner/.rbenv/plugins/rbenv-gem-rehash
echo 'FINISHED installation of rbenv-gem-rehash'
echo '-----------------------------------------'

echo '----------------------------------'
echo 'BEGIN installation of rbenv-update'
mkdir -p "$(rbenv root)/plugins"
git clone https://github.com/rkh/rbenv-update.git "$(rbenv root)/plugins/rbenv-update"
echo 'FINISHED installation of rbenv-update'
echo '-------------------------------------'

echo 'gem: --no-document' > /home/winner/.gemrc
rbenv install -l

export PATH="/home/winner/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv

echo '*************************'
echo 'FINISHED installing rbenv'
echo '*************************'

echo '*******************'
echo 'BEGIN sanity checks'

echo '------'
echo 'whoami'
whoami

echo '--------------'
echo 'sudo --version'
sudo --version

echo '--------------'
echo 'nano --version'
nano --version

echo '--------------'
echo 'tree --version'
tree --version

echo '-------'
echo 'tmux -V'
tmux -V

echo '-----------------------'
echo 'puppet master --version'
puppet master --version

echo '------------'
echo 'chef-solo -v'
chef-solo -v

echo '-----------------'
echo 'ansible --version'
ansible --version

echo '--------------'
echo 'heroku version'
heroku version

echo '---------------'
echo 'redis-server -v'
redis-server -v

echo '----------------'
echo 'sqlite3 -version'
sqlite3 -version

echo '--------------'
echo 'psql --version'
psql --version

echo '---------'
echo 'nodejs -v'
nodejs -v

echo '----------'
echo 'type rbenv'
type rbenv

echo 'COMPLETED sanity checks'
echo '***********************'
